- name: Deploy Filestash
  ansible.builtin.import_tasks: "{{ playbook_dir }}/roles/shared/tasks/docker_compose_service.yml"
  vars:
    service_name: "filestash"
    service_extra_directories:
      - "{{ service_config_dir }}/data"